const REQ_QURAN_LIST = 'REQ_QURAN_LIST';
const REQ_QURAN_LIST_SUCCESS = 'REQ_QURAN_LIST_SUCCESS';
const REQ_QURAN_LIST_FAILURE = 'REQ_QURAN_LIST_FAILURE';

const REQ_QURAN_DETAIL = 'REQ_QURAN_DETAIL';
const REQ_QURAN_DETAIL_SUCCESS = 'REQ_QURAN_DETAIL_SUCCESS';
const REQ_QURAN_DETAIL_FAILURE = 'REQ_QURAN_DETAIL_FAILURE';

export {
  REQ_QURAN_LIST,
  REQ_QURAN_LIST_SUCCESS,
  REQ_QURAN_LIST_FAILURE,
  REQ_QURAN_DETAIL,
  REQ_QURAN_DETAIL_SUCCESS,
  REQ_QURAN_DETAIL_FAILURE,
};
