export const REQ_QURAN_LIST = 'REQ_QURAN_LIST';
export const REQ_QURAN_LIST_SUCCESS = 'REQ_QURAN_LIST_SUCCESS';
export const REQ_QURAN_LIST_FAILED = 'REQ_QURAN_LIST_FAILED';

export const REQ_QURAN_DETAIL = 'REQ_QURAN_DETAIL';
export const REQ_QURAN_DETAIL_SUCCESS = 'REQ_QURAN_DETAIL_SUCCESS';
export const REQ_QURAN_DETAIL_FAILED = 'REQ_QURAN_DETAIL_FAILED';
